name: order_resto
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  badges: ^2.0.2
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.4
  dropdown_search: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_hooks: ^0.18.2+1
  flutter_easyloading: ^3.0.3
  freezed_annotation: ^1.1.0
  geolocator: ^8.2.0
  get_it: ^7.2.0
  go_router: ^3.0.0
  google_fonts: ^2.3.1
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  remixicon: ^1.0.0
  responsive_builder: ^0.4.2
  retrofit: ^3.0.1+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter  
  freezed: ^1.1.1
  hive_generator: ^1.1.2
  injectable_generator: ^1.5.3
  json_serializable: ^6.1.4
  retrofit_generator: ^4.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/illustrations/
